"""add shares_outstanding to assets

Revision ID: 20b055b686eb
Revises: 844280ae9f2f
Create Date: 2026-02-15 17:21:16.783710

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20b055b686eb"
down_revision: str | Sequence[str] | None = "844280ae9f2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assets", sa.Column("shares_outstanding", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assets", "shares_outstanding")
    # ### end Alembic commands ###
