"""add v3_scores table

Revision ID: 271a8ec6b468
Revises: 3209b20e008b
Create Date: 2026-02-17 07:33:16.723515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '271a8ec6b468'
down_revision: Union[str, Sequence[str], None] = '3209b20e008b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v3_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opportunity_type', sa.String(length=20), nullable=False),
    sa.Column('conviction', sa.String(length=20), nullable=False),
    sa.Column('track_a', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('track_b', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('timing_signal', sa.String(length=30), nullable=False),
    sa.Column('max_position_pct', sa.Float(), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v3_scores_asset_id'), 'v3_scores', ['asset_id'], unique=False)
    op.create_index('ix_v3_scores_asset_scored', 'v3_scores', ['asset_id', 'scored_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_v3_scores_asset_scored', table_name='v3_scores')
    op.drop_index(op.f('ix_v3_scores_asset_id'), table_name='v3_scores')
    op.drop_table('v3_scores')
    # ### end Alembic commands ###
