"""add v2 conviction columns to scores

Revision ID: 3209b20e008b
Revises: 4d3c03eb2d62
Create Date: 2026-02-16 22:44:56.951194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3209b20e008b'
down_revision: Union[str, Sequence[str], None] = '4d3c03eb2d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('opportunity_type', sa.String(length=30), nullable=True))
    op.add_column('scores', sa.Column('winning_track', sa.String(length=30), nullable=True))
    op.add_column('scores', sa.Column('asymmetry_ratio', sa.Float(), nullable=True))
    op.add_column('scores', sa.Column('max_position_pct', sa.Float(), nullable=True))
    op.add_column('scores', sa.Column('timing_signal', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'timing_signal')
    op.drop_column('scores', 'max_position_pct')
    op.drop_column('scores', 'asymmetry_ratio')
    op.drop_column('scores', 'winning_track')
    op.drop_column('scores', 'opportunity_type')
    # ### end Alembic commands ###
