"""add_avatar_columns_to_users

Revision ID: 4c4fefbc50d3
Revises: 768260de7cb6
Create Date: 2026-02-16 02:24:34.036585

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4c4fefbc50d3'
down_revision: str | Sequence[str] | None = '768260de7cb6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credential_users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('oauth_avatar_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth_avatar_url')
    op.drop_column('users', 'avatar_url')
    op.drop_column('credential_users', 'avatar_url')
    # ### end Alembic commands ###
