"""add price_target_invalid_reason to scores

Revision ID: 4d3c03eb2d62
Revises: a60167c570ed
Create Date: 2026-02-16 20:02:24.047683

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d3c03eb2d62'
down_revision: str | Sequence[str] | None = 'a60167c570ed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'scores',
        sa.Column('price_target_invalid_reason', sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'price_target_invalid_reason')
    # ### end Alembic commands ###
