"""add_pipeline_models_universe_ingestion_jobs

Revision ID: 768260de7cb6
Revises: 20b055b686eb
Create Date: 2026-02-15 19:55:57.190797

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '768260de7cb6'
down_revision: str | Sequence[str] | None = '20b055b686eb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('progress_detail', sa.String(length=255), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('parent_job_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_job_id'], ['job_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('universe_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('ticker_count', sa.Integer(), nullable=False),
    sa.Column('tickers', sa.JSON().with_variant(
        postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('exclusion_rules', sa.JSON().with_variant(
        postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('tickers_requested', sa.Integer(), nullable=False),
    sa.Column('tickers_succeeded', sa.Integer(), nullable=False),
    sa.Column('tickers_failed', sa.Integer(), nullable=False),
    sa.Column('tickers_skipped', sa.Integer(), nullable=False),
    sa.Column('failed_tickers', sa.JSON().with_variant(
        postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['universe_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_ticker_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('data_fetched', sa.JSON().with_variant(
        postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assets', sa.Column(
        'ingestion_status', sa.String(length=30),
        nullable=False, server_default='active',
    ))
    op.add_column('assets', sa.Column(
        'consecutive_failures', sa.Integer(),
        nullable=False, server_default='0',
    ))
    op.add_column('assets', sa.Column('last_failure_reason', sa.Text(), nullable=True))
    op.add_column('assets', sa.Column('quarantined_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assets', sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'last_retry_at')
    op.drop_column('assets', 'quarantined_at')
    op.drop_column('assets', 'last_failure_reason')
    op.drop_column('assets', 'consecutive_failures')
    op.drop_column('assets', 'ingestion_status')
    op.drop_table('ingestion_ticker_status')
    op.drop_table('ingestion_runs')
    op.drop_table('universe_snapshots')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
