"""add price targets and signal transitions

Revision ID: 844280ae9f2f
Revises: b41b14886872
Create Date: 2026-02-15 00:08:45.109036

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "844280ae9f2f"
down_revision: str | Sequence[str] | None = "b41b14886872"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signal_transitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("previous_signal", sa.String(length=20), nullable=False),
        sa.Column("new_signal", sa.String(length=20), nullable=False),
        sa.Column("previous_conviction", sa.String(length=20), nullable=False),
        sa.Column("new_conviction", sa.String(length=20), nullable=False),
        sa.Column("actual_price_at_transition", sa.Float(), nullable=True),
        sa.Column("intrinsic_value_at_transition", sa.Float(), nullable=True),
        sa.Column("composite_percentile", sa.Float(), nullable=False),
        sa.Column("transitioned_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "asset_id",
            "transitioned_at",
            name="uq_signal_transition_asset_time",
        ),
    )
    op.create_index(
        op.f("ix_signal_transitions_asset_id"),
        "signal_transitions",
        ["asset_id"],
        unique=False,
    )
    op.add_column("scores", sa.Column("intrinsic_value", sa.Float(), nullable=True))
    op.add_column("scores", sa.Column("buy_price", sa.Float(), nullable=True))
    op.add_column("scores", sa.Column("sell_price", sa.Float(), nullable=True))
    op.add_column("scores", sa.Column("actual_price", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scores", "actual_price")
    op.drop_column("scores", "sell_price")
    op.drop_column("scores", "buy_price")
    op.drop_column("scores", "intrinsic_value")
    op.drop_index(op.f("ix_signal_transitions_asset_id"), table_name="signal_transitions")
    op.drop_table("signal_transitions")
    # ### end Alembic commands ###
