"""add_timeseries_and_backtest_tables

Revision ID: a60167c570ed
Revises: a1b2c3d4e5f6
Create Date: 2026-02-16 13:10:00.516079

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a60167c570ed'
down_revision: str | Sequence[str] | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices_intraday',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('time', 'ticker')
    )

    # TimescaleDB-specific DDL (only on PostgreSQL with TimescaleDB, skipped on SQLite)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # Check if TimescaleDB extension is available
        result = bind.execute(sa.text(
            "SELECT EXISTS(SELECT 1 FROM pg_extension WHERE extname = 'timescaledb')"
        ))
        has_timescale = result.scalar()

        if has_timescale:
            op.execute(
                "SELECT create_hypertable('prices_intraday', 'time', "
                "chunk_time_interval => INTERVAL '1 week', if_not_exists => TRUE)"
            )
            op.execute("""
                ALTER TABLE prices_intraday SET (
                    timescaledb.compress,
                    timescaledb.compress_segmentby = 'ticker',
                    timescaledb.compress_orderby = 'time DESC'
                )
            """)
            op.execute(
                "SELECT add_compression_policy('prices_intraday', INTERVAL '7 days')"
            )
            op.execute("""
                CREATE MATERIALIZED VIEW IF NOT EXISTS prices_daily
                WITH (timescaledb.continuous) AS
                SELECT
                    time_bucket('1 day', time) AS date,
                    ticker,
                    first(open, time)  AS open,
                    max(high)           AS high,
                    min(low)            AS low,
                    last(close, time)   AS close,
                    sum(volume)         AS volume
                FROM prices_intraday
                GROUP BY date, ticker
                WITH NO DATA
            """)
            op.execute("""
                SELECT add_continuous_aggregate_policy('prices_daily',
                    start_offset    => INTERVAL '3 days',
                    end_offset      => INTERVAL '1 hour',
                    schedule_interval => INTERVAL '1 hour')
            """)

    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('universe_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.Column('rebalance_frequency', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON().with_variant(
        postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('annualized_return', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('summary_stats', sa.JSON().with_variant(
        postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['universe_snapshot_id'], ['universe_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics_derived',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.String(length=10), nullable=False),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roic', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('ev_ebitda', sa.Float(), nullable=True),
    sa.Column('fcf_yield', sa.Float(), nullable=True),
    sa.Column('return_1m', sa.Float(), nullable=True),
    sa.Column('return_3m', sa.Float(), nullable=True),
    sa.Column('return_6m', sa.Float(), nullable=True),
    sa.Column('return_12m', sa.Float(), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(
        postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        'asset_id', 'as_of_date', name='uq_metrics_asset_date',
    )
    )
    op.create_index('ix_metrics_derived_date', 'metrics_derived', ['as_of_date'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.String(length=10), nullable=False),
    sa.Column('signal', sa.String(length=20), nullable=False),
    sa.Column('conviction_level', sa.String(length=20), nullable=False),
    sa.Column('composite_percentile', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('position_return', sa.Float(), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(
        postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        'run_id', 'asset_id', 'as_of_date', name='uq_backtest_result',
    )
    )
    op.create_index(
        'ix_backtest_results_run_date', 'backtest_results',
        ['run_id', 'as_of_date'], unique=False,
    )
    op.add_column('ingestion_runs', sa.Column(
        'data_types', sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), 'postgresql',
        ), nullable=True,
    ))
    op.add_column('scores', sa.Column('universe_snapshot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'scores_universe_snapshot_id_fkey', 'scores',
        'universe_snapshots', ['universe_snapshot_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP MATERIALIZED VIEW IF EXISTS prices_daily CASCADE")

    op.drop_constraint('scores_universe_snapshot_id_fkey', 'scores', type_='foreignkey')
    op.drop_column('scores', 'universe_snapshot_id')
    op.drop_column('ingestion_runs', 'data_types')
    op.drop_index('ix_backtest_results_run_date', table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index('ix_metrics_derived_date', table_name='metrics_derived')
    op.drop_table('metrics_derived')
    op.drop_table('backtest_runs')
    op.drop_table('prices_intraday')
    # ### end Alembic commands ###
