"""add password_changed_at to credential_users

Revision ID: ad3f8bd4da04
Revises: 3438c11743ce
Create Date: 2026-02-17 23:03:05.578266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3f8bd4da04'
down_revision: Union[str, Sequence[str], None] = '3438c11743ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credential_users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credential_users', 'password_changed_at')
    # ### end Alembic commands ###
