"""add subscription fields and api key event table

Revision ID: b41b14886872
Revises: 4ee2f8646129
Create Date: 2026-02-14 16:38:36.103797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41b14886872'
down_revision: Union[str, Sequence[str], None] = '4ee2f8646129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_events_api_key_id'), 'api_key_events', ['api_key_id'], unique=False)
    op.add_column('api_keys', sa.Column('is_platform_managed', sa.Boolean(), nullable=False))
    op.add_column('api_keys', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('api_keys', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('uq_user_provider'), 'api_keys', type_='unique')
    op.add_column('credential_users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('credential_users', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('credential_users', sa.Column('subscription_plan', sa.String(length=20), nullable=False, server_default='free'))
    op.create_unique_constraint('uq_credential_users_stripe_customer_id', 'credential_users', ['stripe_customer_id'])
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('subscription_plan', sa.String(length=20), nullable=False, server_default='free'))
    op.create_unique_constraint('uq_users_stripe_customer_id', 'users', ['stripe_customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_stripe_customer_id', 'users', type_='unique')
    op.drop_column('users', 'subscription_plan')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_constraint('uq_credential_users_stripe_customer_id', 'credential_users', type_='unique')
    op.drop_column('credential_users', 'subscription_plan')
    op.drop_column('credential_users', 'stripe_subscription_id')
    op.drop_column('credential_users', 'stripe_customer_id')
    op.create_unique_constraint(op.f('uq_user_provider'), 'api_keys', ['user_id', 'provider_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('api_keys', 'revoked_at')
    op.drop_column('api_keys', 'expires_at')
    op.drop_column('api_keys', 'is_platform_managed')
    op.drop_index(op.f('ix_api_key_events_api_key_id'), table_name='api_key_events')
    op.drop_table('api_key_events')
    # ### end Alembic commands ###
