"""add subscription_status and current_period_end columns

Revision ID: d0853ea65359
Revises: 5e4cd67a4c42
Create Date: 2026-02-17 23:06:31.673408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0853ea65359'
down_revision: Union[str, Sequence[str], None] = '5e4cd67a4c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Rename plan values before adding new columns
    op.execute("UPDATE users SET subscription_plan = 'scout' WHERE subscription_plan = 'free'")
    op.execute("UPDATE users SET subscription_plan = 'operator' WHERE subscription_plan = 'margin_invest'")
    op.execute("UPDATE credential_users SET subscription_plan = 'scout' WHERE subscription_plan = 'free'")
    op.execute("UPDATE credential_users SET subscription_plan = 'operator' WHERE subscription_plan = 'margin_invest'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credential_users', sa.Column('subscription_status', sa.String(length=20), nullable=True))
    op.add_column('credential_users', sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_period_end')
    op.drop_column('users', 'subscription_status')
    op.drop_column('credential_users', 'current_period_end')
    op.drop_column('credential_users', 'subscription_status')
    # ### end Alembic commands ###

    # Restore original plan values
    op.execute("UPDATE users SET subscription_plan = 'free' WHERE subscription_plan = 'scout'")
    op.execute("UPDATE users SET subscription_plan = 'margin_invest' WHERE subscription_plan = 'operator'")
    op.execute("UPDATE credential_users SET subscription_plan = 'free' WHERE subscription_plan = 'scout'")
    op.execute("UPDATE credential_users SET subscription_plan = 'margin_invest' WHERE subscription_plan = 'operator'")
    # ### end manual commands ###
