import type { Metadata } from "next"
import Link from "next/link"
import { Navbar } from "@/components/nav/navbar"

export const metadata: Metadata = {
  title: "Terms of Service | Margin Invest",
  description:
    "Terms of Service governing use of the Margin Invest platform, including eligibility, subscriptions, limitations of liability, and dispute resolution.",
}

export default function TermsPage() {
  return (
    <main className="relative bg-bg-primary min-h-screen">
      <div className="relative z-10">
        <Navbar />

        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
          <h1 className="heading-2 text-text-primary mb-4">Terms of Service</h1>
          <p className="text-sm text-text-tertiary mb-12">
            Last updated: February 27, 2026
          </p>

          <div className="space-y-12 text-text-secondary body-text">
            <section>
              <h2 className="heading-3 text-text-primary mb-4">1. Acceptance of Terms</h2>
              <p className="mb-4">
                By accessing or using the Margin Invest platform (&ldquo;the Service&rdquo;), you
                agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not
                agree to these Terms, you must not access or use the Service.
              </p>
              <p>
                We may update these Terms from time to time. Continued use of the Service after
                changes are posted constitutes acceptance of the revised Terms.
              </p>
            </section>

            <section>
              <h2 className="heading-3 text-text-primary mb-4">2. Eligibility</h2>
              <p className="mb-4">
                You must be at least 18 years of age and legally capable of entering into a binding
                agreement in your jurisdiction to use the Service.
              </p>
              <p>
                By using the Service, you represent and warrant that you meet these eligibility
                requirements.
              </p>
            </section>

            <section>
              <h2 className="heading-3 text-text-primary mb-4">3. Service Description</h2>
              <p className="mb-4">
                Margin Invest provides quantitative investment analysis tools, factor-based scoring
                frameworks, and portfolio analytics for informational and educational purposes only.
              </p>
              <p className="mb-4">
                The Service does not provide personalized investment advice, recommendations to buy
                or sell securities, or any form of financial, legal, or tax advice. Use of the
                Service does not create an advisory, fiduciary, or client relationship between you
                and Margin Invest.
              </p>
              <p>
                All scores, rankings, signals, and analytical outputs are generated by deterministic
                quantitative models and are provided strictly for informational purposes. You are
                solely responsible for any investment decisions you make.
              </p>
            </section>

            <section>
              <h2 className="heading-3 text-text-primary mb-4">4. User Accounts</h2>
              <p className="mb-4">
                You are responsible for maintaining the confidentiality of your account credentials
                and for all activities that occur under your account. You must notify us immediately
                of any unauthorized use.
              </p>
              <p>
                We reserve the right to suspend or terminate accounts that violate these Terms or
                engage in abusive, fraudulent, or harmful behavior.
              </p>
            </section>

            <section>
              <h2 className="heading-3 text-text-primary mb-4">5. Subscriptions and Payments</h2>
              <p className="mb-4">
                Certain features of the Service require a paid subscription. Subscription fees are
                billed in advance on a recurring basis (monthly or annually, as selected at
                purchase).
              </p>
              <p className="mb-4">
                You may cancel your subscription at any time. Cancellation takes effect at the end of
                the current billing period. No refunds are provided for partial billing periods
                unless required by applicable law.
              </p>
              <p>
                We reserve the right to change subscription pricing with at least 30 days&apos;
                notice. Price changes apply at the next renewal date.
              </p>
            </section>

            <section>
              <h2 className="heading-3 text-text-primary mb-4">6. Intellectual Property</h2>
              <p className="mb-4">
                All content, software, algorithms, models, data compilations, user interfaces, and
                documentation provided through the Service are the intellectual property of Margin
                Invest or its licensors.
              </p>
              <p>
                You may not copy, modify, distribute, reverse engineer, or create derivative works
                from the Service or its components without prior written consent.
              </p>
            </section>

            <section>
              <h2 className="heading-3 text-text-primary mb-4">7. Prohibited Conduct</h2>
              <p className="mb-4">You agree not to:</p>
              <ul className="list-disc list-inside mb-4 space-y-1 text-text-tertiary">
                <li>Use the Service for any unlawful purpose</li>
                <li>Attempt to gain unauthorized access to any part of the Service</li>
                <li>Interfere with or disrupt the Service or its infrastructure</li>
                <li>Scrape, crawl, or harvest data from the Service without authorization</li>
                <li>Resell, redistribute, or sublicense the Service or its outputs</li>
                <li>Misrepresent the Service&apos;s outputs as personalized investment advice</li>
              </ul>
            </section>

            <section>
              <h2 className="heading-3 text-text-primary mb-4">8. Disclaimers</h2>
              <p className="mb-4">
                THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT
                WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES
                OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
              </p>
              <p className="mb-4">
                Margin Invest does not warrant that the Service will be uninterrupted, error-free,
                or free of harmful components. Model outputs may contain inaccuracies and should not
                be relied upon as the sole basis for any investment decision.
              </p>
              <p>
                Past performance of any scoring model, backtested strategy, or analytical framework
                does not guarantee future results. All investments carry risk, including the possible
                loss of principal.
              </p>
            </section>

            <section>
              <h2 className="heading-3 text-text-primary mb-4">9. Limitation of Liability</h2>
              <p className="mb-4">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, MARGIN INVEST AND ITS OFFICERS, DIRECTORS,
                EMPLOYEES, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
                CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS,
                DATA, OR INVESTMENT LOSSES, ARISING FROM YOUR USE OF THE SERVICE.
              </p>
              <p>
                IN NO EVENT SHALL MARGIN INVEST&apos;S TOTAL LIABILITY EXCEED THE AMOUNT YOU PAID
                FOR THE SERVICE DURING THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
              </p>
            </section>

            <section>
              <h2 className="heading-3 text-text-primary mb-4">10. Indemnification</h2>
              <p>
                You agree to indemnify and hold harmless Margin Invest from any claims, damages,
                losses, or expenses (including reasonable attorneys&apos; fees) arising from your use
                of the Service, violation of these Terms, or infringement of any third-party rights.
              </p>
            </section>

            <section>
              <h2 className="heading-3 text-text-primary mb-4">11. Governing Law and Disputes</h2>
              <p className="mb-4">
                These Terms are governed by the laws of the State of Delaware, without regard to
                conflict of law principles.
              </p>
              <p>
                Any disputes arising under these Terms shall be resolved through binding arbitration
                in accordance with the rules of the American Arbitration Association, unless you opt
                out of arbitration within 30 days of creating your account by emailing{" "}
                <a
                  href="mailto:legal@margin-invest.com"
                  className="text-accent hover:text-accent-hover transition-colors underline underline-offset-2"
                >
                  legal@margin-invest.com
                </a>
                .
              </p>
            </section>

            <section>
              <h2 className="heading-3 text-text-primary mb-4">12. Termination</h2>
              <p className="mb-4">
                We may terminate or suspend your access to the Service at any time, with or without
                cause, upon notice. Upon termination, your right to use the Service ceases
                immediately.
              </p>
              <p>
                Sections 6 (Intellectual Property), 8 (Disclaimers), 9 (Limitation of Liability),
                10 (Indemnification), and 11 (Governing Law) survive termination.
              </p>
            </section>

            <section>
              <h2 className="heading-3 text-text-primary mb-4">13. Contact</h2>
              <p>
                For questions about these Terms, contact:{" "}
                <a
                  href="mailto:legal@margin-invest.com"
                  className="text-accent hover:text-accent-hover transition-colors underline underline-offset-2"
                >
                  legal@margin-invest.com
                </a>
              </p>
            </section>
          </div>

          <div className="mt-16 pt-8 border-t border-border-subtle">
            <Link
              href="/"
              className="text-sm text-text-tertiary hover:text-text-secondary transition-colors"
            >
              &larr; Back to home
            </Link>
          </div>
        </div>
      </div>
    </main>
  )
}
