import type { CandidateCard } from "./types"

export type { CandidateCard }

export const FALLBACK_CANDIDATES: CandidateCard[] = [
  {
    ticker: "AAPL",
    name: "Apple Inc.",
    sector: "Technology",
    actual_price: 173.22,
    buy_price: 214.90,
    margin_of_safety: 0.194,
    composite_percentile: 83,
    conviction_level: "high",
    quality_percentile: 85,
    value_percentile: 62,
    momentum_percentile: 71,
    sentiment_percentile: 68,
    growth_percentile: 74,
    scored_at: new Date().toISOString(),
    filters_passed: 8,
    filters_total: 8,
  },
  {
    ticker: "MSFT",
    name: "Microsoft Corp.",
    sector: "Technology",
    actual_price: 378.91,
    buy_price: 445.00,
    margin_of_safety: 0.149,
    composite_percentile: 79,
    conviction_level: "high",
    quality_percentile: 91,
    value_percentile: 55,
    momentum_percentile: 68,
    sentiment_percentile: 72,
    growth_percentile: 81,
    scored_at: new Date().toISOString(),
    filters_passed: 8,
    filters_total: 8,
  },
  {
    ticker: "JNJ",
    name: "Johnson & Johnson",
    sector: "Healthcare",
    actual_price: 152.44,
    buy_price: 188.30,
    margin_of_safety: 0.190,
    composite_percentile: 76,
    conviction_level: "high",
    quality_percentile: 78,
    value_percentile: 82,
    momentum_percentile: 59,
    sentiment_percentile: 61,
    growth_percentile: 55,
    scored_at: new Date().toISOString(),
    filters_passed: 8,
    filters_total: 8,
  },
  {
    ticker: "COST",
    name: "Costco Wholesale",
    sector: "Consumer Staples",
    actual_price: 591.20,
    buy_price: 710.00,
    margin_of_safety: 0.167,
    composite_percentile: 81,
    conviction_level: "high",
    quality_percentile: 88,
    value_percentile: 48,
    momentum_percentile: 77,
    sentiment_percentile: 75,
    growth_percentile: 70,
    scored_at: new Date().toISOString(),
    filters_passed: 8,
    filters_total: 8,
  },
  {
    ticker: "V",
    name: "Visa Inc.",
    sector: "Financials",
    actual_price: 279.55,
    buy_price: 338.20,
    margin_of_safety: 0.173,
    composite_percentile: 78,
    conviction_level: "high",
    quality_percentile: 82,
    value_percentile: 64,
    momentum_percentile: 73,
    sentiment_percentile: 69,
    growth_percentile: 76,
    scored_at: new Date().toISOString(),
    filters_passed: 8,
    filters_total: 8,
  },
]

export const ENGINE_VERSION = "v1.3.2"
export const FACTOR_MODEL_VERSION = "v2.1"
export const DEFAULT_UNIVERSE_SIZE = 1842
export const DEFAULT_ELIGIBLE_COUNT = 143
