export { HeroSection } from "./sections/hero-section"
export { EvidenceSection } from "./sections/evidence-section"
export { ComparisonSection } from "./sections/comparison-section"
export { PricingSection } from "./sections/pricing-section"
export { FooterSection } from "./sections/footer-section"
